version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-shop
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  shop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop
    restart: always
    ports:
      - 8081:8081
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/shop
      SPRING_REDIS_URL: redis://redis:6379
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mongodb_data:

networks:
  default:
    name: shared_network
    external: true